import { buildMcpAppHtml, isMcpUiAppTool } from "../lib/mcp-apps.js";
import type { ResourceContent, ToolResult } from "../server/runtime-types.js";

interface UiAppResource extends ResourceContent {
  name: string;
  description: string;
  createdAt: string;
}

export class UiAppResourceStore {
  private readonly resources = new Map<string, UiAppResource>();
  private readonly order: string[] = [];

  constructor(
    readonly enabled: boolean,
    private readonly maxResources = 30
  ) {}

  decorate(toolName: string, args: unknown, result: ToolResult): ToolResult {
    if (!this.enabled || !isMcpUiAppTool(toolName) || result.isError) {
      return result;
    }

    const resourceUri = this.put(toolName, args, result);
    const currentUi = result._meta?.ui;
    const currentUiRecord =
      currentUi && typeof currentUi === "object"
        ? (currentUi as Record<string, unknown>)
        : {};

    return {
      ...result,
      _meta: {
        ...(result._meta ?? {}),
        ui: {
          ...currentUiRecord,
          resourceUri,
        },
      },
    };
  }

  list() {
    if (!this.enabled) {
      return [];
    }

    return this.order
      .slice()
      .reverse()
      .map((uri) => this.resources.get(uri))
      .filter((entry): entry is UiAppResource => Boolean(entry))
      .map((entry) => ({
        uri: entry.uri,
        name: entry.name,
        description: `${entry.description} (${entry.createdAt})`,
        mimeType: entry.mimeType,
      }));
  }

  read(uri: string): ResourceContent | null {
    const entry = this.resources.get(uri);
    if (!entry) {
      return null;
    }
    return {
      uri: entry.uri,
      mimeType: entry.mimeType,
      text: entry.text,
    };
  }

  private put(toolName: string, args: unknown, result: ToolResult): string {
    const uid = `${Date.now()}-${Math.random().toString(16).slice(2, 10)}`;
    const uri = `ui://mcp-probe-kit/${toolName}/${uid}`;
    const entry: UiAppResource = {
      uri,
      name: `UI Preview · ${toolName}`,
      description: `MCP Apps preview generated by ${toolName}`,
      mimeType: "text/html",
      text: buildMcpAppHtml(toolName, args, result),
      createdAt: new Date().toISOString(),
    };

    this.resources.set(uri, entry);
    this.order.push(uri);

    while (this.order.length > this.maxResources) {
      const oldest = this.order.shift();
      if (oldest) {
        this.resources.delete(oldest);
      }
    }
    return uri;
  }
}
