# Funding links for GitHub Sponsors
# You can add your funding links here

# github: [mybolide]
# patreon: username
# open_collective: username
# ko_fi: username
# custom: ["https://www.bytezonex.com/"]
