import type { DirectionPreset } from './visual-direction-engine.js';

export const VISUAL_DIRECTION_PRESETS: Record<string, DirectionPreset> = {
  'editorial-precision': {
    id: 'editorial-precision',
    name: 'Editorial Precision',
    rationale: '用排版、对齐、留白和信息顺序建立层级，减少卡片与装饰对专业信息的干扰。',
    personality: ['克制', '精密', '可信', '信息优先'],
    palette: {
      canvas: 'oklch(0.975 0.004 95)',
      surface: 'oklch(1 0 0)',
      text: 'oklch(0.22 0.012 75)',
      mutedText: 'oklch(0.52 0.012 75)',
      line: 'oklch(0.89 0.008 90)',
      accent: 'oklch(0.48 0.085 165)',
      accentStrong: 'oklch(0.40 0.09 165)',
      success: 'oklch(0.55 0.12 145)',
      warning: 'oklch(0.68 0.13 75)',
      danger: 'oklch(0.55 0.18 25)',
    },
    layoutByScreen: {
      'professional-dashboard': '窄侧栏 + 紧凑工具栏 + 宽主画布。优先表格、分区和内联状态，不使用等分卡片瀑布。',
      'content-workspace': '左侧内容导航 + 中央正文 + 可选右侧检查器，正文宽度与工具区分离。',
    },
    defaultLayout: '清晰页面标题区 + 单一主内容流 + 必要的辅助侧区，通过边线和留白分区。',
    navigation: '导航保持窄、稳定、低视觉噪声；当前项使用单一强调色和位置反馈。',
    imagery: '产品界面优先真实数据和结构截图；不使用抽象 3D 球、渐变光斑或装饰性插画填空。',
    componentRules: [
      { component: 'surface', rule: '默认无阴影；使用背景层级、1px 边线和间距区分区域。' },
      { component: 'card', rule: '只有独立对象才使用卡片；同屏卡片不超过 4 个，禁止嵌套卡片。' },
      { component: 'button', rule: '主按钮每个任务区最多 1 个；桌面视觉高度 32-36px、圆角 6px，但命中区必须 ≥44px；移动端控件实际高度 ≥44px。' },
      { component: 'table', rule: '表头弱化、数字右对齐、状态内联、行高 36-44px，操作按频率分层。' },
      { component: 'chart', rule: '先突出基准、趋势与异常；颜色服务语义，不作为装饰。' },
    ],
    avoid: ['巨大标题压过内容', '卡片瀑布', '装饰性统计卡', '发光科技效果'],
  },
  'operational-clarity': {
    id: 'operational-clarity',
    name: 'Operational Clarity',
    rationale: '围绕高频任务、状态变化和批量操作组织界面，让用户快速判断并完成工作。',
    personality: ['高效', '清晰', '稳定', '低干扰'],
    palette: {
      canvas: 'oklch(0.97 0.004 230)',
      surface: 'oklch(1 0 0)',
      text: 'oklch(0.22 0.01 230)',
      mutedText: 'oklch(0.53 0.015 230)',
      line: 'oklch(0.88 0.012 230)',
      accent: 'oklch(0.49 0.075 205)',
      accentStrong: 'oklch(0.41 0.08 205)',
      success: 'oklch(0.55 0.12 145)',
      warning: 'oklch(0.70 0.13 80)',
      danger: 'oklch(0.56 0.18 25)',
    },
    layoutByScreen: {
      'workflow-console': '稳定侧栏 + 页面工具栏 + 主工作区；详情使用抽屉或分栏，不反复跳页。',
      'professional-dashboard': '状态摘要条 + 主要任务区 + 异常队列；摘要只保留影响决策的指标。',
    },
    defaultLayout: '页面标题与操作同一水平线，筛选、列表、详情按工作顺序排列。',
    navigation: '按用户工作域而不是技术模块命名；高频入口固定，低频设置收起。',
    imagery: '不用装饰图片；空间优先留给表格、表单、状态和操作反馈。',
    componentRules: [
      { component: 'toolbar', rule: '主要筛选与主要动作同区；高级筛选折叠，批量动作仅在选中后出现。' },
      { component: 'form', rule: '标签常驻、错误就近、每组不超过 4 个字段，长流程分步。' },
      { component: 'status', rule: '文字为主、颜色辅助；同一状态在全产品只使用一种表达。' },
      { component: 'dialog', rule: '只用于阻断性决策；普通编辑使用抽屉、侧栏或就地编辑。' },
      { component: 'empty-state', rule: '说明为什么为空，并提供唯一下一步，不放大插画。' },
    ],
    avoid: ['功能入口平均铺开', '所有操作同等强调', '多层弹窗', '无意义欢迎页'],
  },
  'calm-trust': {
    id: 'calm-trust',
    name: 'Calm Trust',
    rationale: '通过稳定节奏、明确语言和温和但高对比的视觉系统建立信任，不依赖拟物或柔光效果。',
    personality: ['可靠', '平静', '清楚', '包容'],
    palette: {
      canvas: 'oklch(0.975 0.008 155)',
      surface: 'oklch(1 0 0)',
      text: 'oklch(0.23 0.015 155)',
      mutedText: 'oklch(0.50 0.02 155)',
      line: 'oklch(0.88 0.018 155)',
      accent: 'oklch(0.47 0.075 155)',
      accentStrong: 'oklch(0.39 0.08 155)',
      success: 'oklch(0.54 0.11 145)',
      warning: 'oklch(0.69 0.12 78)',
      danger: 'oklch(0.55 0.17 25)',
    },
    layoutByScreen: {},
    defaultLayout: '单一主任务流 + 清晰说明区 + 必要帮助入口，减少并列决策。',
    navigation: '使用用户能理解的任务语言，当前位置始终可见，返回路径可预测。',
    imagery: '使用真实人物、场景或可信图示；禁止医疗蓝渐变、拟物软阴影和模糊背景。',
    componentRules: [
      { component: 'form', rule: '正文不小于 16px；字段说明前置，错误信息具体且可恢复。' },
      { component: 'alert', rule: '风险等级用标题、正文和图标共同表达，不能只靠颜色。' },
      { component: 'button', rule: '文案描述结果而非泛化动作，如“提交申请”而不是“确定”。' },
      { component: 'help', rule: '帮助与隐私信息就近出现，不隐藏在页脚或二级菜单。' },
    ],
    avoid: ['Neumorphism', '柔光大阴影', '低对比浅灰文字', '只靠颜色表达风险'],
  },
  'product-storytelling': {
    id: 'product-storytelling',
    name: 'Product Storytelling',
    rationale: '用真实内容、编辑式节奏和产品证据形成叙事，而不是堆砌 Hero、Features 和重复 CTA。',
    personality: ['自信', '清晰', '有节奏', '内容驱动'],
    palette: {
      canvas: 'oklch(0.975 0.006 80)',
      surface: 'oklch(1 0 0)',
      text: 'oklch(0.21 0.012 60)',
      mutedText: 'oklch(0.51 0.018 60)',
      line: 'oklch(0.88 0.012 75)',
      accent: 'oklch(0.52 0.13 38)',
      accentStrong: 'oklch(0.43 0.14 38)',
      success: 'oklch(0.55 0.11 145)',
      warning: 'oklch(0.69 0.13 75)',
      danger: 'oklch(0.55 0.18 25)',
    },
    layoutByScreen: {
      'marketing-page': '编辑式首屏 + 产品证据 + 工作方式 + 可信案例 + 单一收口 CTA，区块宽度与节奏有变化。',
    },
    defaultLayout: '一条清晰叙事线，使用真实产品图、数据和案例替代通用功能卡片。',
    navigation: '顶级入口不超过 5 个；主 CTA 全页保持同一意图。',
    imagery: '优先真实产品截图、场景照片和说明性图形；图片承担信息，不只做氛围。',
    componentRules: [
      { component: 'hero', rule: '标题直接表达产品价值，正文不超过 3 行；首屏最多 2 个动作。' },
      { component: 'proof', rule: '用真实数据、客户结果或产品画面证明，不使用空泛 logo 墙。' },
      { component: 'section', rule: '连续区块必须在宽度、对齐或内容形态上形成节奏变化。' },
      { component: 'cta', rule: '全页只保留一个主意图，末尾 CTA 不重复首屏文案。' },
    ],
    avoid: ['Hero + 三等分功能卡 + CTA 套路', '重复口号', '抽象渐变背景', '无证据的大数字'],
  },
  'commerce-focus': {
    id: 'commerce-focus',
    name: 'Commerce Focus',
    rationale: '围绕发现、比较、信任和购买决策组织内容，让商品信息而不是装饰成为视觉中心。',
    personality: ['直接', '可信', '清楚', '转化克制'],
    palette: {
      canvas: 'oklch(0.98 0.006 70)',
      surface: 'oklch(1 0 0)',
      text: 'oklch(0.22 0.012 55)',
      mutedText: 'oklch(0.51 0.016 55)',
      line: 'oklch(0.89 0.012 70)',
      accent: 'oklch(0.48 0.14 28)',
      accentStrong: 'oklch(0.40 0.15 28)',
      success: 'oklch(0.54 0.12 145)',
      warning: 'oklch(0.70 0.13 78)',
      danger: 'oklch(0.55 0.18 25)',
    },
    layoutByScreen: {
      'commerce-catalog': '筛选和排序靠近商品列表；商品卡突出图、名称、价格与关键差异，减少营销徽章。',
      'commerce-detail': '媒体区与购买区并列，核心规格、交付、保障和评价按决策顺序展开。',
    },
    defaultLayout: '分类、筛选、商品内容和购买动作按用户决策顺序排列。',
    navigation: '分类层级可预测，搜索始终可达，购物车状态明确。',
    imagery: '统一比例、真实清晰、背景克制；不使用低质生成图或不一致裁切。',
    componentRules: [
      { component: 'product-card', rule: '只展示比较所需字段；禁止每张卡堆满标签、阴影和多个按钮。' },
      { component: 'price', rule: '价格层级明确，优惠说明可验证，不制造虚假紧迫感。' },
      { component: 'purchase', rule: '库存、配送、退换和支付信息靠近主购买动作。' },
      { component: 'review', rule: '展示分布和代表性内容，不只展示平均星级。' },
    ],
    avoid: ['虚假倒计时', '过量促销色', '每张商品卡多个 CTA', '标签与徽章堆叠'],
  },
};
