import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import {
  listToolDefinitions,
  prepareAppOnlyToolsForList,
} from '../src/server/tool-registry.js';
import {
  MCP_APPS_EXTENSION_ID,
  MCP_APP_MIME_TYPE,
} from '../src/lib/mcp-apps.js';

type JsonSchema = {
  type?: string | string[];
  description?: string;
  enum?: unknown[];
  items?: JsonSchema;
  properties?: Record<string, JsonSchema>;
  required?: string[];
};

type Manifest = {
  version: string;
  toolsets: {
    compact: { tools: string[] };
    memoryConditional: { tools: string[] };
    full: { count: number };
  };
  structuredOutput?: {
    schemas?: Record<string, string>;
  };
};

const root = resolve(import.meta.dirname, '..');
const outputPath = resolve(root, 'docs', 'data', 'tools.js');
const manifest = JSON.parse(
  await readFile(resolve(root, 'tools-manifest.json'), 'utf8'),
) as Manifest;

const compact = new Set(manifest.toolsets.compact.tools);
const memory = new Set(manifest.toolsets.memoryConditional.tools);
const outputSchemas = manifest.structuredOutput?.schemas ?? {};

const categoryMap: Record<string, { key: string; title: string; icon: string }> = {
  orchestration: { key: 'workflow', title: '编排入口', icon: '🔄' },
  routing: { key: 'routing', title: '工具选择兜底', icon: '🧭' },
  'project-spec': { key: 'project', title: '项目与规格', icon: '📁' },
  'code-analysis': { key: 'analysis', title: '代码分析与测试', icon: '🔍' },
  git: { key: 'git', title: 'Git 工具', icon: '📝' },
  ui: { key: 'uiux', title: 'UI/UX', icon: '🎨' },
  memory: { key: 'memory', title: 'Memory', icon: '🧠' },
  'plan-control': { key: 'plan', title: '计划状态与收敛', icon: '🔁' },
  interactive: { key: 'interactive', title: '交互与访谈', icon: '💬' },
  'app-only': { key: 'apps', title: 'MCP Apps 专用', icon: '◫' },
};

function schemaType(schema: JsonSchema): string {
  if (Array.isArray(schema.type)) return schema.type.join(' | ');
  if (schema.enum?.length) return schema.enum.map(String).join(' | ');
  if (schema.type === 'array') {
    return `array<${schema.items ? schemaType(schema.items) : 'unknown'}>`;
  }
  return schema.type ?? 'unknown';
}

function paramsFromInput(inputSchema: JsonSchema | undefined) {
  const properties = inputSchema?.properties ?? {};
  const required = new Set(inputSchema?.required ?? []);
  return Object.entries(properties).map(([name, schema]) => ({
    name,
    type: schemaType(schema),
    required: required.has(name),
    desc: schema.description ?? '',
  }));
}

function surfaceFor(name: string): 'default' | 'memory' | 'compatibility' {
  if (compact.has(name)) return 'default';
  if (memory.has(name)) return 'memory';
  return 'compatibility';
}

const categories: Record<string, { title: string; icon: string }> = {};
const groups: Record<string, unknown[]> = {};

for (const definition of listToolDefinitions()) {
  const category = categoryMap[definition.skillRoute.groupId];
  if (!category) throw new Error(`Missing docs category for ${definition.skillRoute.groupId}`);
  categories[category.key] = { title: category.title, icon: category.icon };
  groups[category.key] ??= [];
  groups[category.key].push({
    name: definition.name,
    description: definition.schema.description,
    schema: outputSchemas[definition.name] ?? (definition.outputSchema ? 'structuredContent' : 'text'),
    params: paramsFromInput(definition.schema.inputSchema as JsonSchema),
    usage: definition.skillRoute.whenToCall,
    surface: surfaceFor(definition.name),
  });
}

const appTools = prepareAppOnlyToolsForList({
  clientCapabilities: {
    extensions: {
      [MCP_APPS_EXTENSION_ID]: { mimeTypes: [MCP_APP_MIME_TYPE] },
    },
  },
  uiAppsEnabled: true,
});

if (appTools.length) {
  const category = categoryMap['app-only'];
  categories[category.key] = { title: category.title, icon: category.icon };
  groups[category.key] = appTools.map((tool) => ({
    name: tool.name,
    description: tool.description,
    schema: 'App-only structuredContent',
    params: paramsFromInput(tool.inputSchema as JsonSchema),
    usage: '仅由协商成功的 MCP App 调用，不进入模型可见工具面。',
    surface: 'app-only',
  }));
}

const generated = {
  version: manifest.version,
  counts: {
    default: compact.size,
    withMemory: compact.size + memory.size,
    full: manifest.toolsets.full.count,
    appOnly: appTools.length,
  },
  categories,
  ...groups,
};

const source = `// AUTO-GENERATED by scripts/sync-doc-tools.ts. Do not edit manually.\n` +
  `const toolsData = ${JSON.stringify(generated, null, 2)};\n`;
await writeFile(outputPath, source, 'utf8');
console.log(
  `[sync-doc-tools] ${Object.values(groups).reduce((sum, items) => sum + items.length, 0)} entries -> ${outputPath}`,
);
