import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, describe, expect, test } from "vitest";
import { VERSION } from "../../version.js";
import {
  ensureAgentsMdSkillReference,
  ensureMcpProbeKitBootstrap,
  ensureMcpProbeKitBootstrapForToolCall,
  ensureMcpProbeKitBootstrapAtStartup,
  ensureMcpProbeSkill,
  resolveProjectRootFromToolArgs,
} from "../workflow-skill-installer.js";
import {
  formatSkillVersionMarker,
  agentsContextNeedsUpgrade,
  compareSemver,
  skillContentNeedsUpgrade,
} from "../workflow-skill-version.js";
import {
  formatSkillFrontmatter,
  generateWorkflowSkillContent,
  LEGACY_WORKFLOW_SKILL_REL_PATH,
  MCP_PROBE_SKILL_REL_PATH,
} from "../workflow-skill-template.js";
import { wrapMcpProbeBlock } from "../merge-agents-md.js";

const tempDirs: string[] = [];

afterEach(() => {
  while (tempDirs.length > 0) {
    const dir = tempDirs.pop();
    if (dir) {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  }
});

describe("workflow-skill-version", () => {
  test("compareSemver 比较完整 SemVer", () => {
    expect(compareSemver("3.5.0", "3.5.1")).toBeLessThan(0);
    expect(compareSemver("3.6.0", "3.5.9")).toBeGreaterThan(0);
    expect(compareSemver("3.5.0", "3.5.0")).toBe(0);
    expect(compareSemver("4.0.0-rc.2", "4.0.0-rc.3")).toBeLessThan(0);
    expect(compareSemver("4.0.0-rc.10", "4.0.0-rc.3")).toBeGreaterThan(0);
    expect(compareSemver("4.0.0-rc.3", "4.0.0")).toBeLessThan(0);
    expect(compareSemver("4.0.0", "4.0.0-rc.99")).toBeGreaterThan(0);
  });

  test("旧进程保留更高版本旧格式 Skill 与自定义 AGENTS 块", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-higher-legacy-"));
    tempDirs.push(root);
    const higherVersion = "9.9.9";
    const skillPath = path.join(root, MCP_PROBE_SKILL_REL_PATH);
    fs.mkdirSync(path.dirname(skillPath), { recursive: true });
    fs.writeFileSync(
      skillPath,
      `${formatSkillVersionMarker(higherVersion)}\n# KEEP_HIGH_SKILL\n`,
      "utf8",
    );
    fs.writeFileSync(
      path.join(root, "AGENTS.md"),
      [
        "<!-- mcp-probe:context begin — generated by newer kit -->",
        `<!-- mcp-probe:context-version: ${higherVersion} -->`,
        "## MCP（必须先调）",
        "KEEP_HIGH_AGENTS",
        "<!-- mcp-probe:context end -->",
        "",
        "# User rules",
        "KEEP_USER",
      ].join("\n"),
      "utf8",
    );

    const result = ensureMcpProbeKitBootstrap(root);
    const skill = fs.readFileSync(skillPath, "utf8");
    const agents = fs.readFileSync(path.join(root, "AGENTS.md"), "utf8");

    expect(result.skill.version).toBe(higherVersion);
    expect(result.skill.updated).toBe(false);
    expect(result.agentsMd.updated).toBe(false);
    expect(result.cliFallback?.version).toBe(higherVersion);
    expect(skill).toContain("KEEP_HIGH_SKILL");
    expect(agents).toContain("KEEP_HIGH_AGENTS");
    expect(agents).toContain("KEEP_USER");
  });

  test("重复托管块中存在更高版本时保留最高版本块并清理低版本重复块", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-agents-mixed-version-"));
    tempDirs.push(root);
    ensureMcpProbeSkill(root);
    const agentsPath = path.join(root, "AGENTS.md");
    const original = [
      "<!-- mcp-probe:context begin -->",
      `<!-- mcp-probe:context-version: ${VERSION} -->`,
      "LOWER_BLOCK_FIRST",
      "<!-- mcp-probe:context end -->",
      "",
      "<!-- mcp-probe:context begin — generated by newer kit -->",
      "<!-- mcp-probe:context-version: 9.9.9 -->",
      "KEEP_HIGHER_BLOCK",
      "<!-- mcp-probe:context end -->",
      "",
      "# User rules",
      "KEEP_USER_CONTENT",
    ].join("\n");
    fs.writeFileSync(agentsPath, original, "utf8");

    const result = ensureMcpProbeKitBootstrap(root);
    const agents = fs.readFileSync(agentsPath, "utf8");

    expect(result.agentsMd.updated).toBe(true);
    expect((agents.match(/<!-- mcp-probe:context begin/g) ?? [])).toHaveLength(1);
    expect((agents.match(/<!-- mcp-probe:context end -->/g) ?? [])).toHaveLength(1);
    expect(agents).toContain("<!-- mcp-probe:context-version: 9.9.9 -->");
    expect(agents).toContain("KEEP_HIGHER_BLOCK");
    expect(agents).toContain("KEEP_USER_CONTENT");
    expect(agents).not.toContain("LOWER_BLOCK_FIRST");
    expect(agents).not.toContain(`mcp-probe:context-version: ${VERSION}`);
  });

  test("无版本标记视为需要升级", () => {
    expect(skillContentNeedsUpgrade("# custom", VERSION)).toBe(true);
    expect(agentsContextNeedsUpgrade("<!-- mcp-probe:context begin -->", VERSION)).toBe(true);
  });
});

describe("workflow-skill-installer", () => {
  test("缺失时创建 mcp-probe-kit Skill", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-"));
    tempDirs.push(root);

    const result = ensureMcpProbeSkill(root);

    expect(result.created).toBe(true);
    expect(result.updated).toBe(false);
    expect(result.version).toBe(VERSION);
    const text = fs.readFileSync(path.join(root, MCP_PROBE_SKILL_REL_PATH), "utf8");
    expect(text).toContain('name: mcp-probe-kit');
    expect(text).toContain('mcp-probe-kit-version:');
    expect(text).toContain("MCP 调用时机");
  });

  test("仅 HTML 注释同版本会升级为 frontmatter", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-"));
    tempDirs.push(root);
    const skillPath = path.join(root, MCP_PROBE_SKILL_REL_PATH);
    const content = `${formatSkillVersionMarker(VERSION)}\n# same version\n`;
    fs.mkdirSync(path.dirname(skillPath), { recursive: true });
    fs.writeFileSync(skillPath, content, "utf8");

    const result = ensureMcpProbeSkill(root);

    expect(result.updated).toBe(true);
    const text = fs.readFileSync(skillPath, "utf8");
    expect(text).toContain("name: mcp-probe-kit");
    expect(text).not.toBe(content);
  });

  test("标准 frontmatter 同版本不覆盖", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-"));
    tempDirs.push(root);
    const skillPath = path.join(root, MCP_PROBE_SKILL_REL_PATH);
    const content = generateWorkflowSkillContent(VERSION);
    fs.mkdirSync(path.dirname(skillPath), { recursive: true });
    fs.writeFileSync(skillPath, content, "utf8");

    const result = ensureMcpProbeSkill(root);

    expect(result.created).toBe(false);
    expect(result.updated).toBe(false);
    expect(fs.readFileSync(skillPath, "utf8")).toBe(content);
  });

  test("rc.2 Skill 会自动升级到当前安装版本", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-"));
    tempDirs.push(root);
    const skillPath = path.join(root, MCP_PROBE_SKILL_REL_PATH);
    const content = generateWorkflowSkillContent("4.0.0-rc.2");
    fs.mkdirSync(path.dirname(skillPath), { recursive: true });
    fs.writeFileSync(skillPath, content, "utf8");

    const result = ensureMcpProbeSkill(root);

    expect(result.updated).toBe(true);
    expect(result.previousVersion).toBe("4.0.0-rc.2");
    expect(fs.readFileSync(skillPath, "utf8")).toContain(
      `mcp-probe-kit-version: "${VERSION}"`
    );
  });

  test("高于当前安装版本的 Skill 不会被降级", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-"));
    tempDirs.push(root);
    const skillPath = path.join(root, MCP_PROBE_SKILL_REL_PATH);
    const content = generateWorkflowSkillContent("999.0.0");
    fs.mkdirSync(path.dirname(skillPath), { recursive: true });
    fs.writeFileSync(skillPath, content, "utf8");

    const result = ensureMcpProbeSkill(root);

    expect(result.updated).toBe(false);
    expect(result.previousVersion).toBe("999.0.0");
    expect(fs.readFileSync(skillPath, "utf8")).toBe(content);
  });

  test("旧版 HTML 注释 Skill 会升级", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-"));
    tempDirs.push(root);
    const skillPath = path.join(root, MCP_PROBE_SKILL_REL_PATH);
    fs.mkdirSync(path.dirname(skillPath), { recursive: true });
    fs.writeFileSync(
      skillPath,
      `${formatSkillVersionMarker("0.1.0")}\n# stale tools list\n`,
      "utf8"
    );

    const result = ensureMcpProbeSkill(root);

    expect(result.updated).toBe(true);
    expect(result.previousVersion).toBe("0.1.0");
    const text = fs.readFileSync(skillPath, "utf8");
    expect(text).toContain('name: mcp-probe-kit');
    expect(text).toContain("何时调用");
    expect(text).not.toContain("stale tools list");
  });

  test("无 AGENTS.md 时创建并 @ 引用 Skill", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-"));
    tempDirs.push(root);

    const result = ensureAgentsMdSkillReference(root);

    expect(result.created).toBe(true);
    const agents = fs.readFileSync(path.join(root, "AGENTS.md"), "utf8");
    expect(agents).toContain("mcp-probe:context-version");
    expect(agents).toContain(MCP_PROBE_SKILL_REL_PATH);
    expect(agents).toContain(`@${MCP_PROBE_SKILL_REL_PATH}`);
  });

  test("已有 AGENTS.md 但缺 Skill 引用时更新", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-"));
    tempDirs.push(root);
    fs.writeFileSync(path.join(root, "AGENTS.md"), "# Custom rules\n", "utf8");

    const result = ensureAgentsMdSkillReference(root);

    expect(result.updated).toBe(true);
    const agents = fs.readFileSync(path.join(root, "AGENTS.md"), "utf8");
    expect(agents).toContain("# Custom rules");
    expect(agents).toContain(MCP_PROBE_SKILL_REL_PATH);
  });

  test("旧 workflow Skill 路径会触发 AGENTS.md 更新", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-"));
    tempDirs.push(root);
    const legacyBlock = wrapMcpProbeBlock(
      `## MCP\nSee [skill](${LEGACY_WORKFLOW_SKILL_REL_PATH})`,
      "0.1.0"
    );
    fs.writeFileSync(path.join(root, "AGENTS.md"), `${legacyBlock}\n`, "utf8");

    const result = ensureAgentsMdSkillReference(root);

    expect(result.updated).toBe(true);
    const agents = fs.readFileSync(path.join(root, "AGENTS.md"), "utf8");
    expect(agents).toContain(MCP_PROBE_SKILL_REL_PATH);
    expect(agents).toContain(`mcp-probe:context-version: ${VERSION}`);
  });

  test("同版本 AGENTS 托管块内容漂移时自动刷新并保留用户规则", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-same-version-drift-"));
    tempDirs.push(root);
    ensureMcpProbeSkill(root);
    const staleInner = [
      "## MCP (call first)",
      `Requires mcp-probe-kit. @${MCP_PROBE_SKILL_REL_PATH}`,
      "- Unsure which MCP → `workflow` (returns firstTool)",
      "- Bug → `start_bugfix` (searches memory first)",
    ].join("\n");
    const staleBlock = wrapMcpProbeBlock(staleInner, VERSION);
    fs.writeFileSync(
      path.join(root, "AGENTS.md"),
      `${staleBlock}\n\n# User rules\nkeep-this-line\n`,
      "utf8",
    );

    const result = ensureAgentsMdSkillReference(root, VERSION);
    const agents = fs.readFileSync(path.join(root, "AGENTS.md"), "utf8");

    expect(result.updated).toBe(true);
    expect(agents).toContain("call `resume_plan` first");
    expect(agents).toContain("pass only `project_root`");
    expect(agents).toContain("Do not explore with Bash");
    expect(agents).toContain("# User rules");
    expect(agents).toContain("keep-this-line");

    const second = ensureAgentsMdSkillReference(root, VERSION);
    expect(second.updated).toBe(false);
    expect(fs.readFileSync(path.join(root, "AGENTS.md"), "utf8")).toBe(agents);
  });

  test("当前版本存在重复 mcp-probe 块时也必须自动修复为单块", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-duplicate-"));
    tempDirs.push(root);
    ensureMcpProbeSkill(root);
    const inner = `## MCP（必须先调）\n@${MCP_PROBE_SKILL_REL_PATH}`;
    const block = wrapMcpProbeBlock(inner, VERSION);
    fs.writeFileSync(path.join(root, "AGENTS.md"), `${block}\n\n${block}\n`, "utf8");

    const result = ensureAgentsMdSkillReference(root, VERSION);
    const agents = fs.readFileSync(path.join(root, "AGENTS.md"), "utf8");

    expect(result.updated).toBe(true);
    expect((agents.match(/<!-- mcp-probe:context begin/g) ?? [])).toHaveLength(1);
    expect((agents.match(/^## MCP(?:（必须先调）| \(call first\))$/gm) ?? [])).toHaveLength(1);

    const second = ensureAgentsMdSkillReference(root, VERSION);
    const agentsAfterSecondSync = fs.readFileSync(path.join(root, "AGENTS.md"), "utf8");
    expect(second.updated).toBe(false);
    expect(agentsAfterSecondSync).toBe(agents);
  });

  test("已有多份旧指导片段时连续 20 次 bootstrap 始终只保留一份", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-repeat-"));
    tempDirs.push(root);
    fs.writeFileSync(path.join(root, "README.md"), "# 测试项目\n", "utf8");
    const legacySection = [
      "## MCP（必须先调）",
      "需已配置 mcp-probe-kit。",
      "- 新功能 → `start_feature`",
      "- 缺上下文 → `init_project_context`",
    ].join("\n");
    fs.writeFileSync(
      path.join(root, "AGENTS.md"),
      `${Array(8).fill(legacySection).join("\n\n")}\n\n# 用户规则\n保留此行\n`,
      "utf8",
    );

    let stableContent = "";
    for (let iteration = 0; iteration < 20; iteration += 1) {
      ensureMcpProbeKitBootstrap(root);
      const agents = fs.readFileSync(path.join(root, "AGENTS.md"), "utf8");
      expect((agents.match(/<!-- mcp-probe:context begin/g) ?? [])).toHaveLength(1);
      expect((agents.match(/<!-- mcp-probe:context end -->/g) ?? [])).toHaveLength(1);
      expect((agents.match(/^## MCP(?:（必须先调）| \(call first\))$/gm) ?? [])).toHaveLength(1);
      expect(agents).toContain("# 用户规则");
      expect(agents).toContain("保留此行");
      if (iteration === 0) {
        stableContent = agents;
      } else {
        expect(agents).toBe(stableContent);
      }
    }
  });

  test("bootstrap 同时处理 Skill 与 AGENTS.md", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-"));
    tempDirs.push(root);

    const result = ensureMcpProbeKitBootstrap(root);

    expect(result.skill.created).toBe(true);
    expect(result.agentsMd.created).toBe(true);
    expect(result.cliFallback?.version).toBe(VERSION);
    expect(fs.existsSync(path.join(root, ".mcp-probe-kit/runtime.json"))).toBe(true);
    expect(fs.existsSync(path.join(root, ".mcp-probe-kit/bin/probe.ps1"))).toBe(true);
  });

  test("MCP 启动时在已确认工作区自动升级 Skill", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-"));
    tempDirs.push(root);
    const skillPath = path.join(root, MCP_PROBE_SKILL_REL_PATH);
    fs.mkdirSync(path.dirname(skillPath), { recursive: true });
    fs.writeFileSync(skillPath, generateWorkflowSkillContent("4.0.0-rc.2"), "utf8");

    const result = ensureMcpProbeKitBootstrapAtStartup(root);

    expect(result.error).toBeUndefined();
    expect(result.workspace.source).toBe("explicit");
    expect(result.bootstrap?.skill.updated).toBe(true);
    expect(result.bootstrap?.skill.previousVersion).toBe("4.0.0-rc.2");
    expect(fs.readFileSync(skillPath, "utf8")).toContain(
      `mcp-probe-kit-version: "${VERSION}"`
    );

    const second = ensureMcpProbeKitBootstrapAtStartup(root);
    expect(second.bootstrap?.skill.created).toBe(false);
    expect(second.bootstrap?.skill.updated).toBe(false);
  });

  test("旧进程不会降低项目内更高版本的 Skill、AGENTS 和 CLI", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-"));
    tempDirs.push(root);
    const higherVersion = "999.0.0";
    const skillPath = path.join(root, MCP_PROBE_SKILL_REL_PATH);
    fs.mkdirSync(path.dirname(skillPath), { recursive: true });
    fs.mkdirSync(path.join(root, ".cursor"), { recursive: true });
    fs.writeFileSync(skillPath, generateWorkflowSkillContent(higherVersion), "utf8");

    const result = ensureMcpProbeKitBootstrap(root);

    expect(result.skill.version).toBe(higherVersion);
    expect(result.cliFallback?.version).toBe(higherVersion);
    expect(fs.readFileSync(path.join(root, "AGENTS.md"), "utf8")).toContain(
      `mcp-probe:context-version: ${higherVersion}`
    );
    expect(
      fs.readFileSync(path.join(root, ".cursor/rules/mcp-probe-kit.mdc"), "utf8")
    ).toContain(`mcp-probe-kit@${higherVersion}`);
  });

  test("从 tool args 解析 project_root", () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), "wf-skill-"));
    tempDirs.push(root);
    expect(resolveProjectRootFromToolArgs({ project_root: root })).toBe(path.resolve(root));
  });

  test("非创建型工具拒绝不存在的显式 project_root 且不落盘", () => {
    const parent = fs.mkdtempSync(path.join(os.tmpdir(), "wf-invalid-root-"));
    tempDirs.push(parent);
    const missing = path.join(parent, "does-not-exist");

    expect(() =>
      ensureMcpProbeKitBootstrapForToolCall("code_insight", { project_root: missing })
    ).toThrow(/项目目录不存在/);
    expect(fs.existsSync(missing)).toBe(false);
  });
});
